-- 150_rbac_submenu_permissions_extra.sql
-- No-op — sebelumnya migration ini men-seed 112 permission level-submenu
-- untuk: attendance.corrections/admin/employee-shifts/exempt-positions/
-- sessions/reports, careerintelligence.paths/successions/development,
-- leave.accrual-policies/reasons, performance.kpi/okr,
-- recruitment.assessments/internal-candidates/offers, dan seluruh
-- setting.* / workforceintelligence.* submenu.
--
-- Semua nama itu sudah tidak dipakai lagi — organization/setting/employee/
-- employeemovement/payroll/workforceintelligence/careerintelligence tidak
-- lagi punya submenu sama sekali, dan attendance/leave/performance/
-- recruitment sudah dikonsolidasi ke submenu yang lebih sedikit (lihat
-- migration 149, yang sudah meng-cover pengganti semua nama di atas).
-- Isi migration ini dihapus karena seluruhnya sudah digantikan/basi, bukan
-- untuk menghindari rewrite migration yang sudah applied di production
-- (baru ada 1 tenant dev/test yang sempat menjalankannya, dan sudah
-- di-rollback).
