package tenantseed

import (
	"time"

	"gorm.io/gorm"
)

// ── Nationalities (tenant) ──
// Sumber: docs/seeder/CountriesTableSeeder.php (ISO 3166-1 alpha-2, 240 negara) + "Lainnya / Other"
// Schema: id(char(36) UUID deterministik), code(varchar(20)), name, sort_order, timestamps, deleted_at
// Sebelumnya tabel countries & nationalities duplikat; keputusan: hanya nationalities yang dipakai.
func seedNationalities(db *gorm.DB) (int, int, error) {
	data := []map[string]interface{}{
		{"id": codeToUUID("nationality", "US"), "code": "US", "name": "United States", "sort_order": 1, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "CA"), "code": "CA", "name": "Canada", "sort_order": 2, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "AF"), "code": "AF", "name": "Afghanistan", "sort_order": 3, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "AL"), "code": "AL", "name": "Albania", "sort_order": 4, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "DZ"), "code": "DZ", "name": "Algeria", "sort_order": 5, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "AS"), "code": "AS", "name": "American Samoa", "sort_order": 6, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "AD"), "code": "AD", "name": "Andorra", "sort_order": 7, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "AO"), "code": "AO", "name": "Angola", "sort_order": 8, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "AI"), "code": "AI", "name": "Anguilla", "sort_order": 9, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "AQ"), "code": "AQ", "name": "Antarctica", "sort_order": 10, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "AG"), "code": "AG", "name": "Antigua and/or Barbuda", "sort_order": 11, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "AR"), "code": "AR", "name": "Argentina", "sort_order": 12, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "AM"), "code": "AM", "name": "Armenia", "sort_order": 13, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "AW"), "code": "AW", "name": "Aruba", "sort_order": 14, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "AU"), "code": "AU", "name": "Australia", "sort_order": 15, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "AT"), "code": "AT", "name": "Austria", "sort_order": 16, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "AZ"), "code": "AZ", "name": "Azerbaijan", "sort_order": 17, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "BS"), "code": "BS", "name": "Bahamas", "sort_order": 18, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "BH"), "code": "BH", "name": "Bahrain", "sort_order": 19, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "BD"), "code": "BD", "name": "Bangladesh", "sort_order": 20, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "BB"), "code": "BB", "name": "Barbados", "sort_order": 21, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "BY"), "code": "BY", "name": "Belarus", "sort_order": 22, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "BE"), "code": "BE", "name": "Belgium", "sort_order": 23, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "BZ"), "code": "BZ", "name": "Belize", "sort_order": 24, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "BJ"), "code": "BJ", "name": "Benin", "sort_order": 25, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "BM"), "code": "BM", "name": "Bermuda", "sort_order": 26, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "BT"), "code": "BT", "name": "Bhutan", "sort_order": 27, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "BO"), "code": "BO", "name": "Bolivia", "sort_order": 28, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "BA"), "code": "BA", "name": "Bosnia and Herzegovina", "sort_order": 29, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "BW"), "code": "BW", "name": "Botswana", "sort_order": 30, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "BV"), "code": "BV", "name": "Bouvet Island", "sort_order": 31, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "BR"), "code": "BR", "name": "Brazil", "sort_order": 32, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "IO"), "code": "IO", "name": "British lndian Ocean Territory", "sort_order": 33, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "BN"), "code": "BN", "name": "Brunei Darussalam", "sort_order": 34, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "BG"), "code": "BG", "name": "Bulgaria", "sort_order": 35, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "BF"), "code": "BF", "name": "Burkina Faso", "sort_order": 36, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "BI"), "code": "BI", "name": "Burundi", "sort_order": 37, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "KH"), "code": "KH", "name": "Cambodia", "sort_order": 38, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "CM"), "code": "CM", "name": "Cameroon", "sort_order": 39, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "CV"), "code": "CV", "name": "Cape Verde", "sort_order": 40, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "KY"), "code": "KY", "name": "Cayman Islands", "sort_order": 41, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "CF"), "code": "CF", "name": "Central African Republic", "sort_order": 42, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "TD"), "code": "TD", "name": "Chad", "sort_order": 43, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "CL"), "code": "CL", "name": "Chile", "sort_order": 44, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "CN"), "code": "CN", "name": "China", "sort_order": 45, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "CX"), "code": "CX", "name": "Christmas Island", "sort_order": 46, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "CC"), "code": "CC", "name": "Cocos (Keeling) Islands", "sort_order": 47, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "CO"), "code": "CO", "name": "Colombia", "sort_order": 48, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "KM"), "code": "KM", "name": "Comoros", "sort_order": 49, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "CG"), "code": "CG", "name": "Congo", "sort_order": 50, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "CK"), "code": "CK", "name": "Cook Islands", "sort_order": 51, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "CR"), "code": "CR", "name": "Costa Rica", "sort_order": 52, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "HR"), "code": "HR", "name": "Croatia (Hrvatska)", "sort_order": 53, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "CU"), "code": "CU", "name": "Cuba", "sort_order": 54, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "CY"), "code": "CY", "name": "Cyprus", "sort_order": 55, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "CZ"), "code": "CZ", "name": "Czech Republic", "sort_order": 56, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "CD"), "code": "CD", "name": "Democratic Republic of Congo", "sort_order": 57, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "DK"), "code": "DK", "name": "Denmark", "sort_order": 58, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "DJ"), "code": "DJ", "name": "Djibouti", "sort_order": 59, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "DM"), "code": "DM", "name": "Dominica", "sort_order": 60, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "DO"), "code": "DO", "name": "Dominican Republic", "sort_order": 61, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "TP"), "code": "TP", "name": "East Timor", "sort_order": 62, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "EC"), "code": "EC", "name": "Ecudaor", "sort_order": 63, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "EG"), "code": "EG", "name": "Egypt", "sort_order": 64, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "SV"), "code": "SV", "name": "El Salvador", "sort_order": 65, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "GQ"), "code": "GQ", "name": "Equatorial Guinea", "sort_order": 66, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "ER"), "code": "ER", "name": "Eritrea", "sort_order": 67, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "EE"), "code": "EE", "name": "Estonia", "sort_order": 68, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "ET"), "code": "ET", "name": "Ethiopia", "sort_order": 69, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "FK"), "code": "FK", "name": "Falkland Islands (Malvinas)", "sort_order": 70, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "FO"), "code": "FO", "name": "Faroe Islands", "sort_order": 71, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "FJ"), "code": "FJ", "name": "Fiji", "sort_order": 72, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "FI"), "code": "FI", "name": "Finland", "sort_order": 73, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "FR"), "code": "FR", "name": "France", "sort_order": 74, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "FX"), "code": "FX", "name": "France, Metropolitan", "sort_order": 75, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "GF"), "code": "GF", "name": "French Guiana", "sort_order": 76, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "PF"), "code": "PF", "name": "French Polynesia", "sort_order": 77, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "TF"), "code": "TF", "name": "French Southern Territories", "sort_order": 78, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "GA"), "code": "GA", "name": "Gabon", "sort_order": 79, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "GM"), "code": "GM", "name": "Gambia", "sort_order": 80, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "GE"), "code": "GE", "name": "Georgia", "sort_order": 81, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "DE"), "code": "DE", "name": "Germany", "sort_order": 82, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "GH"), "code": "GH", "name": "Ghana", "sort_order": 83, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "GI"), "code": "GI", "name": "Gibraltar", "sort_order": 84, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "GR"), "code": "GR", "name": "Greece", "sort_order": 85, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "GL"), "code": "GL", "name": "Greenland", "sort_order": 86, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "GD"), "code": "GD", "name": "Grenada", "sort_order": 87, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "GP"), "code": "GP", "name": "Guadeloupe", "sort_order": 88, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "GU"), "code": "GU", "name": "Guam", "sort_order": 89, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "GT"), "code": "GT", "name": "Guatemala", "sort_order": 90, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "GN"), "code": "GN", "name": "Guinea", "sort_order": 91, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "GW"), "code": "GW", "name": "Guinea-Bissau", "sort_order": 92, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "GY"), "code": "GY", "name": "Guyana", "sort_order": 93, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "HT"), "code": "HT", "name": "Haiti", "sort_order": 94, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "HM"), "code": "HM", "name": "Heard and Mc Donald Islands", "sort_order": 95, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "HN"), "code": "HN", "name": "Honduras", "sort_order": 96, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "HK"), "code": "HK", "name": "Hong Kong", "sort_order": 97, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "HU"), "code": "HU", "name": "Hungary", "sort_order": 98, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "IS"), "code": "IS", "name": "Iceland", "sort_order": 99, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "IN"), "code": "IN", "name": "India", "sort_order": 100, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "ID"), "code": "ID", "name": "Indonesia", "sort_order": 101, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "IR"), "code": "IR", "name": "Iran (Islamic Republic of)", "sort_order": 102, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "IQ"), "code": "IQ", "name": "Iraq", "sort_order": 103, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "IE"), "code": "IE", "name": "Ireland", "sort_order": 104, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "IL"), "code": "IL", "name": "Israel", "sort_order": 105, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "IT"), "code": "IT", "name": "Italy", "sort_order": 106, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "CI"), "code": "CI", "name": "Ivory Coast", "sort_order": 107, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "JM"), "code": "JM", "name": "Jamaica", "sort_order": 108, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "JP"), "code": "JP", "name": "Japan", "sort_order": 109, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "JO"), "code": "JO", "name": "Jordan", "sort_order": 110, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "KZ"), "code": "KZ", "name": "Kazakhstan", "sort_order": 111, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "KE"), "code": "KE", "name": "Kenya", "sort_order": 112, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "KI"), "code": "KI", "name": "Kiribati", "sort_order": 113, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "KR"), "code": "KR", "name": "Korea, Republic of", "sort_order": 114, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "KW"), "code": "KW", "name": "Kuwait", "sort_order": 115, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "KG"), "code": "KG", "name": "Kyrgyzstan", "sort_order": 116, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "LV"), "code": "LV", "name": "Latvia", "sort_order": 117, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "LB"), "code": "LB", "name": "Lebanon", "sort_order": 118, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "LS"), "code": "LS", "name": "Lesotho", "sort_order": 119, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "LR"), "code": "LR", "name": "Liberia", "sort_order": 120, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "LY"), "code": "LY", "name": "Libyan Arab Jamahiriya", "sort_order": 121, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "LI"), "code": "LI", "name": "Liechtenstein", "sort_order": 122, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "LT"), "code": "LT", "name": "Lithuania", "sort_order": 123, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "LU"), "code": "LU", "name": "Luxembourg", "sort_order": 124, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "MO"), "code": "MO", "name": "Macau", "sort_order": 125, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "MK"), "code": "MK", "name": "Macedonia", "sort_order": 126, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "MG"), "code": "MG", "name": "Madagascar", "sort_order": 127, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "MW"), "code": "MW", "name": "Malawi", "sort_order": 128, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "MY"), "code": "MY", "name": "Malaysia", "sort_order": 129, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "MV"), "code": "MV", "name": "Maldives", "sort_order": 130, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "ML"), "code": "ML", "name": "Mali", "sort_order": 131, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "MT"), "code": "MT", "name": "Malta", "sort_order": 132, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "MH"), "code": "MH", "name": "Marshall Islands", "sort_order": 133, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "MQ"), "code": "MQ", "name": "Martinique", "sort_order": 134, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "MR"), "code": "MR", "name": "Mauritania", "sort_order": 135, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "MU"), "code": "MU", "name": "Mauritius", "sort_order": 136, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "TY"), "code": "TY", "name": "Mayotte", "sort_order": 137, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "MX"), "code": "MX", "name": "Mexico", "sort_order": 138, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "FM"), "code": "FM", "name": "Micronesia, Federated States of", "sort_order": 139, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "MD"), "code": "MD", "name": "Moldova, Republic of", "sort_order": 140, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "MC"), "code": "MC", "name": "Monaco", "sort_order": 141, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "MN"), "code": "MN", "name": "Mongolia", "sort_order": 142, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "MS"), "code": "MS", "name": "Montserrat", "sort_order": 143, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "MA"), "code": "MA", "name": "Morocco", "sort_order": 144, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "MZ"), "code": "MZ", "name": "Mozambique", "sort_order": 145, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "MM"), "code": "MM", "name": "Myanmar", "sort_order": 146, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "NA"), "code": "NA", "name": "Namibia", "sort_order": 147, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "NR"), "code": "NR", "name": "Nauru", "sort_order": 148, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "NP"), "code": "NP", "name": "Nepal", "sort_order": 149, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "NL"), "code": "NL", "name": "Netherlands", "sort_order": 150, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "AN"), "code": "AN", "name": "Netherlands Antilles", "sort_order": 151, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "NC"), "code": "NC", "name": "New Caledonia", "sort_order": 152, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "NZ"), "code": "NZ", "name": "New Zealand", "sort_order": 153, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "NI"), "code": "NI", "name": "Nicaragua", "sort_order": 154, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "NE"), "code": "NE", "name": "Niger", "sort_order": 155, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "NG"), "code": "NG", "name": "Nigeria", "sort_order": 156, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "NU"), "code": "NU", "name": "Niue", "sort_order": 157, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "NF"), "code": "NF", "name": "Norfork Island", "sort_order": 158, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "MP"), "code": "MP", "name": "Northern Mariana Islands", "sort_order": 159, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "NO"), "code": "NO", "name": "Norway", "sort_order": 160, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "OM"), "code": "OM", "name": "Oman", "sort_order": 161, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "PK"), "code": "PK", "name": "Pakistan", "sort_order": 162, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "PW"), "code": "PW", "name": "Palau", "sort_order": 163, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "PA"), "code": "PA", "name": "Panama", "sort_order": 164, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "PG"), "code": "PG", "name": "Papua New Guinea", "sort_order": 165, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "PY"), "code": "PY", "name": "Paraguay", "sort_order": 166, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "PE"), "code": "PE", "name": "Peru", "sort_order": 167, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "PH"), "code": "PH", "name": "Philippines", "sort_order": 168, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "PN"), "code": "PN", "name": "Pitcairn", "sort_order": 169, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "PL"), "code": "PL", "name": "Poland", "sort_order": 170, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "PT"), "code": "PT", "name": "Portugal", "sort_order": 171, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "PR"), "code": "PR", "name": "Puerto Rico", "sort_order": 172, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "QA"), "code": "QA", "name": "Qatar", "sort_order": 173, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "SS"), "code": "SS", "name": "Republic of South Sudan", "sort_order": 174, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "RE"), "code": "RE", "name": "Reunion", "sort_order": 175, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "RO"), "code": "RO", "name": "Romania", "sort_order": 176, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "RU"), "code": "RU", "name": "Russian Federation", "sort_order": 177, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "RW"), "code": "RW", "name": "Rwanda", "sort_order": 178, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "KN"), "code": "KN", "name": "Saint Kitts and Nevis", "sort_order": 179, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "LC"), "code": "LC", "name": "Saint Lucia", "sort_order": 180, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "VC"), "code": "VC", "name": "Saint Vincent and the Grenadines", "sort_order": 181, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "WS"), "code": "WS", "name": "Samoa", "sort_order": 182, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "SM"), "code": "SM", "name": "San Marino", "sort_order": 183, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "ST"), "code": "ST", "name": "Sao Tome and Principe", "sort_order": 184, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "SA"), "code": "SA", "name": "Saudi Arabia", "sort_order": 185, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "SN"), "code": "SN", "name": "Senegal", "sort_order": 186, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "RS"), "code": "RS", "name": "Serbia", "sort_order": 187, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "SC"), "code": "SC", "name": "Seychelles", "sort_order": 188, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "SL"), "code": "SL", "name": "Sierra Leone", "sort_order": 189, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "SG"), "code": "SG", "name": "Singapore", "sort_order": 190, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "SK"), "code": "SK", "name": "Slovakia", "sort_order": 191, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "SI"), "code": "SI", "name": "Slovenia", "sort_order": 192, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "SB"), "code": "SB", "name": "Solomon Islands", "sort_order": 193, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "SO"), "code": "SO", "name": "Somalia", "sort_order": 194, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "ZA"), "code": "ZA", "name": "South Africa", "sort_order": 195, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "GS"), "code": "GS", "name": "South Georgia South Sandwich Islands", "sort_order": 196, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "ES"), "code": "ES", "name": "Spain", "sort_order": 197, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "LK"), "code": "LK", "name": "Sri Lanka", "sort_order": 198, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "SH"), "code": "SH", "name": "St. Helena", "sort_order": 199, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "PM"), "code": "PM", "name": "St. Pierre and Miquelon", "sort_order": 200, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "SD"), "code": "SD", "name": "Sudan", "sort_order": 201, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "SR"), "code": "SR", "name": "Suriname", "sort_order": 202, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "SJ"), "code": "SJ", "name": "Svalbarn and Jan Mayen Islands", "sort_order": 203, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "SZ"), "code": "SZ", "name": "Swaziland", "sort_order": 204, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "SE"), "code": "SE", "name": "Sweden", "sort_order": 205, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "CH"), "code": "CH", "name": "Switzerland", "sort_order": 206, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "SY"), "code": "SY", "name": "Syrian Arab Republic", "sort_order": 207, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "TW"), "code": "TW", "name": "Taiwan", "sort_order": 208, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "TJ"), "code": "TJ", "name": "Tajikistan", "sort_order": 209, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "TZ"), "code": "TZ", "name": "Tanzania, United Republic of", "sort_order": 210, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "TH"), "code": "TH", "name": "Thailand", "sort_order": 211, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "TG"), "code": "TG", "name": "Togo", "sort_order": 212, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "TK"), "code": "TK", "name": "Tokelau", "sort_order": 213, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "TO"), "code": "TO", "name": "Tonga", "sort_order": 214, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "TT"), "code": "TT", "name": "Trinidad and Tobago", "sort_order": 215, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "TN"), "code": "TN", "name": "Tunisia", "sort_order": 216, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "TR"), "code": "TR", "name": "Turkey", "sort_order": 217, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "TM"), "code": "TM", "name": "Turkmenistan", "sort_order": 218, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "TC"), "code": "TC", "name": "Turks and Caicos Islands", "sort_order": 219, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "TV"), "code": "TV", "name": "Tuvalu", "sort_order": 220, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "UG"), "code": "UG", "name": "Uganda", "sort_order": 221, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "UA"), "code": "UA", "name": "Ukraine", "sort_order": 222, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "AE"), "code": "AE", "name": "United Arab Emirates", "sort_order": 223, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "GB"), "code": "GB", "name": "United Kingdom", "sort_order": 224, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "UM"), "code": "UM", "name": "United States minor outlying islands", "sort_order": 225, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "UY"), "code": "UY", "name": "Uruguay", "sort_order": 226, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "UZ"), "code": "UZ", "name": "Uzbekistan", "sort_order": 227, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "VU"), "code": "VU", "name": "Vanuatu", "sort_order": 228, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "VA"), "code": "VA", "name": "Vatican City State", "sort_order": 229, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "VE"), "code": "VE", "name": "Venezuela", "sort_order": 230, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "VN"), "code": "VN", "name": "Vietnam", "sort_order": 231, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "VG"), "code": "VG", "name": "Virgin Islands (British)", "sort_order": 232, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "VI"), "code": "VI", "name": "Virgin Islands (U.S.)", "sort_order": 233, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "WF"), "code": "WF", "name": "Wallis and Futuna Islands", "sort_order": 234, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "EH"), "code": "EH", "name": "Western Sahara", "sort_order": 235, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "YE"), "code": "YE", "name": "Yemen", "sort_order": 236, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "YU"), "code": "YU", "name": "Yugoslavia", "sort_order": 237, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "ZR"), "code": "ZR", "name": "Zaire", "sort_order": 238, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "ZM"), "code": "ZM", "name": "Zambia", "sort_order": 239, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "ZW"), "code": "ZW", "name": "Zimbabwe", "sort_order": 240, "created_at": time.Now(), "updated_at": time.Now()},
		{"id": codeToUUID("nationality", "LNY"), "code": "LNY", "name": "Lainnya / Other", "sort_order": 999, "created_at": time.Now(), "updated_at": time.Now()},
	}
	return batchInsert(db, "nationalities", data, 50)
}
